server:
  port: 5000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: command_account_service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: c_account_service_consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
